### ISSUE TITLE
Generate UID For Emergencies

### ISSUE THREAD

**Issue by merktassel** [MKS-Elixr/jubilant-umbrella#41]
Right now our server returns the internal SQL row of each emergency to use as an identifier. It would be much better if we created a unique three digit identifier for each emergency to reference instead. Chris already has some of the code written and implemented on the frontend for it.

**Comment by cse25** [comment]
Here's the function Mark references above.  The function in its current state outputs a five digit pseudo-random alphanumeric string.  Four or five digits would be fine.

``` Javascript
function pseudoRandomString() {
    return Math.round((Math.pow(36, 6) - Math.random() * Math.pow(36, 5))).toString(36).slice(1)
}
```
