### ISSUE TITLE
Timestamp Format

### ISSUE THREAD

**Issue by merktassel** [MKS-Elixr/jubilant-umbrella#43]
What timestamp format does our server use?

**Comment by lbai001** [comment]
Sat May 07 2016 17:02:01 GMT-0700 (PDT), that format, i dont know the name of it

**Comment by merktassel** [comment]
Could you find out for us? Angular is having issues parsing it without explicitly specifying what standard it's based on. We were able to log it out and look at it, but we don't know what format your server is using.

**Comment by lbai001** [comment]
UTC i think

**Comment by lbai001** [comment]
http://dev.mysql.com/doc/refman/5.7/en/datetime.html

**Comment by merktassel** [comment]
Hmm... UTC isn't really a format, so let me know if you find anything else in that link.
